//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
using System.Linq;
using System;
using System.Collections.Generic;
// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class SSC
{
    private string dateFormat = "{0:ddMMyyyy}";
    private object[] itemsField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("MethodContext", typeof(SSCMethodContext), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlElementAttribute("Payload", typeof(SSCPayload), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlElementAttribute("SunSystemsContext", typeof(SSCSunSystemsContext), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public object[] Items
    {
        get
        {
            return this.itemsField;
        }
        set
        {
            this.itemsField = value;
        }
    }

    [Obsolete("DataRepository used to perform the contra")]
    public void ContraXML(string TransactionType)
    {

        if (!TransactionType.Equals("Original"))
        {
            SSCMethodContext sscMethodContext = (SSCMethodContext)Items[1];

            //Description = 0 : Contra, so not required to specify a batchid, infact there wouldnt be one!
            sscMethodContext.LedgerPostingParameters.ElementAt(0).Description = "0";

            SSCPayload payload = (SSCPayload)Items[2];
            int ledgerLineNumer = 0;

            payload.Ledger.ToList().ForEach(line =>
            {
                line.BaseAmount = Contra(line.BaseAmount);
                line.TransactionAmount = Contra(line.TransactionAmount);
                line.MemoAmount = (Convert.ToDecimal(line.MemoAmount) * -1).ToString();

                line.DetailLad.GeneralDescription5 = Contra(line.DetailLad.GeneralDescription5);
                line.DetailLad.GeneralDescription10 = Contra(line.DetailLad.GeneralDescription10);
                line.DetailLad.GeneralDescription11 = Contra(line.DetailLad.GeneralDescription11);
                line.DetailLad.GeneralDescription12 = Contra(line.DetailLad.GeneralDescription12);
                line.DetailLad.GeneralDescription16 = DecideCCOpenTransactionType();


                line.DebitCredit = GetDebitOrCreditBasedOnLedgerLine(ref ledgerLineNumer, line.BaseAmount);

            });

            Items[2] = payload;
        }


    }

    //Logic Taken from "LiveSupport_usp_open_acc_xmlSSCTransaction_NS" and Value taken from "Contra Sun Script from PPWiki"
    private string DecideCCOpenTransactionType()
    {
        return "0"; // 3 : SADJ - Account Adjustment
    }

    //Logic Taken from "LiveSupport_usp_open_acc_xmlSSCTransaction_NS" stored proc
    private string GetDebitOrCreditBasedOnLedgerLine(ref int ledgerLineNumer, string baseAmount)
    {
        double BaseAmount = Convert.ToDouble(baseAmount);
        switch (ledgerLineNumer++)
        {
            case 0:
                if (BaseAmount > 0)
                    return "C";
                else
                    return "D";
            case 1:
                if (BaseAmount > 0)
                    return "D";
                else
                    return "C";
            case 2:
                if (BaseAmount > 0)
                    return "D";
                else
                    return "C";
            case 3:
                if (BaseAmount > 0)
                    return "C";
                else
                    return "D";
            default:
                throw new InvalidOperationException();
        }
    }

    private string Contra(string stringToContra)
    {
        return (Convert.ToDecimal(stringToContra) * -1).ToString();
    }

    public XmlSerializerNamespaces GetNameSpace()
    {
        XmlSerializerNamespaces namespaces = new XmlSerializerNamespaces();
        namespaces.Add("", "");
        return namespaces;
    }

    public void ProcessXML_AppendCharacterToTransactionReference(char? appendChar)
    {
        if (!appendChar.HasValue)
            return;

        SSCPayload payload = (SSCPayload)Items[2];
        payload.Ledger.ToList().ForEach(line =>
        {
            line.TransactionReference = line.TransactionReference + appendChar;
        });
    }

    public void ProcessXML_ConvertTestXMLToLive(string p)
    {
        SSCSunSystemsContext sunSystemsContext = (SSCSunSystemsContext)this.Items[0];
        sunSystemsContext.BusinessUnit = p;
        SSCPayload payload = (SSCPayload)Items[2];
        payload.Ledger.ToList().ForEach(line => { line.JournalSource = p; });
    }

    public void ProcessXML(OpenTraderSunFixes.Model.SunFixAttributes sunFixAttributes)
    {
        if (sunFixAttributes.AppendChar != null)
            ProcessXML_AppendCharacterToTransactionReference(sunFixAttributes.AppendChar);

        if (sunFixAttributes.PostingDate.HasValue)
            ProcessXML_ChangePostingDate(sunFixAttributes.PostingDate.Value.Date);

    }

    private void ProcessXML_ChangePostingDate(DateTime datePosted)
    {
        string dateValuePosted = String.Format(dateFormat, datePosted);
        SSCPayload payload = (SSCPayload)Items[2];
        payload.Ledger.ToList().ForEach(line => line.DetailLad.GeneralDate2 = dateValuePosted);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class SSCMethodContext
{

    private SSCMethodContextLedgerPostingParameters[] ledgerPostingParametersField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("LedgerPostingParameters", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public SSCMethodContextLedgerPostingParameters[] LedgerPostingParameters
    {
        get
        {
            return this.ledgerPostingParametersField;
        }
        set
        {
            this.ledgerPostingParametersField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class SSCMethodContextLedgerPostingParameters
{

    private string descriptionField;

    private string postingTypeField;

    private string defaultPeriodField;

    private string suppressSubstitutedMessagesField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Description
    {
        get
        {
            return this.descriptionField;
        }
        set
        {
            this.descriptionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PostingType
    {
        get
        {
            return this.postingTypeField;
        }
        set
        {
            this.postingTypeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DefaultPeriod
    {
        get
        {
            return this.defaultPeriodField;
        }
        set
        {
            this.defaultPeriodField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SuppressSubstitutedMessages
    {
        get
        {
            return this.suppressSubstitutedMessagesField;
        }
        set
        {
            this.suppressSubstitutedMessagesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class SSCPayload
{

    private SSCPayloadLedgerLine[] ledgerField;

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Line", typeof(SSCPayloadLedgerLine), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    public SSCPayloadLedgerLine[] Ledger
    {
        get
        {
            return this.ledgerField;
        }
        set
        {
            this.ledgerField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class SSCPayloadLedgerLine
{

    private string accountCodeField;

    private string accountingPeriodField;

    private string analysisCode1Field;

    private string analysisCode2Field;

    private string analysisCode3Field;

    private string analysisCode4Field;

    private string analysisCode5Field;

    private string analysisCode6Field;

    private string analysisCode7Field;

    private string analysisCode8Field;

    private string analysisCode9Field;

    private string analysisCode10Field;

    private string baseAmountField;

    private string currencyCodeField;

    private string debitCreditField;

    private string descriptionField;

    private string entryDateField;

    private string journalSourceField;

    private string journalTypeField;

    private string transactionAmountField;

    private string transactionAmountDecimalPlacesField;

    private string transactionDateField;

    private string transactionReferenceField;

    private string memoAmountField;

    private SSCPayloadLedgerLineDetailLad detailLadField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AccountCode
    {
        get
        {
            return this.accountCodeField;
        }
        set
        {
            this.accountCodeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AccountingPeriod
    {
        get
        {
            return this.accountingPeriodField;
        }
        set
        {
            this.accountingPeriodField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AnalysisCode1
    {
        get
        {
            return this.analysisCode1Field;
        }
        set
        {
            this.analysisCode1Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AnalysisCode2
    {
        get
        {
            return this.analysisCode2Field;
        }
        set
        {
            this.analysisCode2Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AnalysisCode3
    {
        get
        {
            return this.analysisCode3Field;
        }
        set
        {
            this.analysisCode3Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AnalysisCode4
    {
        get
        {
            return this.analysisCode4Field;
        }
        set
        {
            this.analysisCode4Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AnalysisCode5
    {
        get
        {
            return this.analysisCode5Field;
        }
        set
        {
            this.analysisCode5Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AnalysisCode6
    {
        get
        {
            return this.analysisCode6Field;
        }
        set
        {
            this.analysisCode6Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AnalysisCode7
    {
        get
        {
            return this.analysisCode7Field;
        }
        set
        {
            this.analysisCode7Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AnalysisCode8
    {
        get
        {
            return this.analysisCode8Field;
        }
        set
        {
            this.analysisCode8Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AnalysisCode9
    {
        get
        {
            return this.analysisCode9Field;
        }
        set
        {
            this.analysisCode9Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AnalysisCode10
    {
        get
        {
            return this.analysisCode10Field;
        }
        set
        {
            this.analysisCode10Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BaseAmount
    {
        get
        {
            return this.baseAmountField;
        }
        set
        {
            this.baseAmountField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CurrencyCode
    {
        get
        {
            return this.currencyCodeField;
        }
        set
        {
            this.currencyCodeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DebitCredit
    {
        get
        {
            return this.debitCreditField;
        }
        set
        {
            this.debitCreditField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Description
    {
        get
        {
            return this.descriptionField;
        }
        set
        {
            this.descriptionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string EntryDate
    {
        get
        {
            return this.entryDateField;
        }
        set
        {
            this.entryDateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string JournalSource
    {
        get
        {
            return this.journalSourceField;
        }
        set
        {
            this.journalSourceField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string JournalType
    {
        get
        {
            return this.journalTypeField;
        }
        set
        {
            this.journalTypeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TransactionAmount
    {
        get
        {
            return this.transactionAmountField;
        }
        set
        {
            this.transactionAmountField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TransactionAmountDecimalPlaces
    {
        get
        {
            return this.transactionAmountDecimalPlacesField;
        }
        set
        {
            this.transactionAmountDecimalPlacesField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TransactionDate
    {
        get
        {
            return this.transactionDateField;
        }
        set
        {
            this.transactionDateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TransactionReference
    {
        get
        {
            return this.transactionReferenceField;
        }
        set
        {
            this.transactionReferenceField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MemoAmount
    {
        get
        {
            return this.memoAmountField;
        }
        set
        {
            this.memoAmountField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DetailLad", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public SSCPayloadLedgerLineDetailLad DetailLad
    {
        get
        {
            return this.detailLadField;
        }
        set
        {
            this.detailLadField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class SSCPayloadLedgerLineDetailLad
{

    private string generalDescription1Field;

    private string generalDescription2Field;

    private string generalDescription3Field;

    private string generalDescription4Field;

    private string generalDescription5Field;

    private string generalDescription6Field;

    private string generalDescription7Field;

    private string generalDescription8Field;

    private string generalDescription9Field;

    private string generalDescription10Field;

    private string generalDescription11Field;

    private string generalDescription12Field;

    private string generalDescription13Field;

    private string generalDescription14Field;

    private string generalDescription15Field;

    private string generalDescription16Field;

    private string generalDescription18Field;

    private string generalDate1Field;

    private string generalDate2Field;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string GeneralDescription1
    {
        get
        {
            return this.generalDescription1Field;
        }
        set
        {
            this.generalDescription1Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string GeneralDescription2
    {
        get
        {
            return this.generalDescription2Field;
        }
        set
        {
            this.generalDescription2Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string GeneralDescription3
    {
        get
        {
            return this.generalDescription3Field;
        }
        set
        {
            this.generalDescription3Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string GeneralDescription4
    {
        get
        {
            return this.generalDescription4Field;
        }
        set
        {
            this.generalDescription4Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string GeneralDescription5
    {
        get
        {
            return this.generalDescription5Field;
        }
        set
        {
            this.generalDescription5Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string GeneralDescription6
    {
        get
        {
            return this.generalDescription6Field;
        }
        set
        {
            this.generalDescription6Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string GeneralDescription7
    {
        get
        {
            return this.generalDescription7Field;
        }
        set
        {
            this.generalDescription7Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string GeneralDescription8
    {
        get
        {
            return this.generalDescription8Field;
        }
        set
        {
            this.generalDescription8Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string GeneralDescription9
    {
        get
        {
            return this.generalDescription9Field;
        }
        set
        {
            this.generalDescription9Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string GeneralDescription10
    {
        get
        {
            return this.generalDescription10Field;
        }
        set
        {
            this.generalDescription10Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string GeneralDescription11
    {
        get
        {
            return this.generalDescription11Field;
        }
        set
        {
            this.generalDescription11Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string GeneralDescription12
    {
        get
        {
            return this.generalDescription12Field;
        }
        set
        {
            this.generalDescription12Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string GeneralDescription13
    {
        get
        {
            return this.generalDescription13Field;
        }
        set
        {
            this.generalDescription13Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string GeneralDescription14
    {
        get
        {
            return this.generalDescription14Field;
        }
        set
        {
            this.generalDescription14Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string GeneralDescription15
    {
        get
        {
            return this.generalDescription15Field;
        }
        set
        {
            this.generalDescription15Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string GeneralDescription16
    {
        get
        {
            return this.generalDescription16Field;
        }
        set
        {
            this.generalDescription16Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string GeneralDescription18
    {
        get
        {
            return this.generalDescription18Field;
        }
        set
        {
            this.generalDescription18Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string GeneralDate1
    {
        get
        {
            return this.generalDate1Field;
        }
        set
        {
            this.generalDate1Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string GeneralDate2
    {
        get
        {
            return this.generalDate2Field;
        }
        set
        {
            this.generalDate2Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class SSCSunSystemsContext
{

    private string businessUnitField;

    private string budgetCodeField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BusinessUnit
    {
        get
        {
            return this.businessUnitField;
        }
        set
        {
            this.businessUnitField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BudgetCode
    {
        get
        {
            return this.budgetCodeField;
        }
        set
        {
            this.budgetCodeField = value;
        }
    }
}
